on: push

jobs:
  npm-build:
    name: 项目打包
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      - name: 安装依赖 执行打包命令
        run: |
          npm install
          run: npm run build
